name: Python Build + Pypi Upload

on:
  push:
    branches: [master, feature/python_bindings]
    tags: ["v*.*.*"]
  pull_request:
    branches: [master]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      working-directory: wrappers/python
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade cibuildwheel
    - name: Build wheels
      uses: joerick/cibuildwheel@v1.10.0
      with:
        package-dir: ./wrappers/python
        output-dir: ./wrappers/python/wheelhouse
    - uses: actions/upload-artifact@v2
      with:
        path: ./wrappers/python/wheelhouse/*.whl

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Build sdist
      working-directory: wrappers/python
      run: |
        python setup.py sdist
    - uses: actions/upload-artifact@v2
      with:
        path: dist/*.tar.gz

  upload-pypi:
    name: Deploy
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest
    # only run if the commit is tagged...
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: artifact
          path: dist

      - uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
          # To test: repository_url: https://test.pypi.org/legacy/
